# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7274f6e924151e0ed2691029624f7e8aa4f810571b6d71db6bfe6e111fb2e55b1b8150ba31a90451277feb80dbabd4ba71510a3e186fd3f3f9fb78332fa5acb7

test:
  secret_key_base: b829a721712fed582da123f34a8cf038a631cfcbe3f26b5574ead316783307b7818745e576e500e488127fa88a7cc675d281528abdbf5796d31b77609f1dd622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
